#!/bin/bash

virtualenv venv
./venv/bin/pip install -r requirements.pip
./venv/bin/python manage.py migrate
./venv/bin/python manage.py loaddata testapp/fixtures/initial_data.json
./venv/bin/python manage.py runserver 127.0.0.1:8888

